# Generated by Django 6.0 on 2026-01-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_attendance_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
